#:schema node_modules/wrangler/config-schema.json
name = "squint-sol"
main = "src/index.ts"
compatibility_date = "2024-06-20"
# compatibility_flags = ["nodejs_compat"]
node_compat = true
# Default environment variables
[vars]
SOLANA_RPC = "https://api.mainnet-beta.solana.com"
ANOTHER_VARIABLE = "value"

# Development-specific environment variables
[env.dev]
vars = { SOLANA_RPC = "https://api.devnet.solana.com" }

# Production-specific environment variables
[env.production]
vars = { SOLANA_RPC = "https://api.mainnet-beta.solana.com" }
